name: squid
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://conda.anaconda.org/pytorch/linux-64
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - absl-py=0.9.0=py36_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.13.2=py36h2e261b9_0
  - cloudpickle=1.3.0=py_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.11.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - faiss-gpu=1.6.3=py36h1a5d453_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.6.1=py36_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.11.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.16.0=py36_0
  - jinja2=2.10.3=py_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - more-itertools=8.0.2=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - notebook=6.0.2=py36_0
  - olefile=0.46=py36_0
  - openssl=1.1.1h=h516909a_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - pango=1.42.4=h049681c_0
  - parso=0.5.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py36_1
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python-spams=2.6.1=py36h2738dde_1204
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pywavelets=1.0.3=py36hdd07704_1
  - pyzmq=18.1.0=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py36he6710b0_0
  - send2trash=1.5.0=py36_0
  - setuptools=45.1.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=1.14.0=py36hf484d3e_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h7b6447c_0
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - anykeystore==0.2
    - astor==0.8.1
    - chainer==7.2.0
    - chainercv==0.13.1
    - chardet==3.0.4
    - chumpy==0.70
    - cmake==3.18.2.post1
    - cryptacular==1.6.2
    - cycler==0.10.0
    - cython==0.29.23
    - dataclasses==0.8
    - einops==0.3.2
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.3.3
    - greenlet==1.1.2
    - grpcio==1.26.0
    - hupper==1.10.3
    - idna==2.9
    - imagecodecs==2020.5.30
    - importlib-metadata==4.8.2
    - ipywidgets==7.5.1
    - isodate==0.6.0
    - joblib==0.14.1
    - jsonpatch==1.32
    - jsonpointer==2.2
    - matplotlib==3.1.2
    - mlxtend==0.18.0
    - msgpack==1.0.0
    - msgpack-numpy==0.4.4.3
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opencv-python==4.1.2.30
    - packaging==20.9
    - pandas==1.0.3
    - pastedeploy==2.1.1
    - pbkdf2==1.3
    - plaster==1.0
    - plaster-pastedeploy==0.7
    - plyfile==0.7.2
    - protobuf==3.11.2
    - psutil==5.7.0
    - pyramid==2.0
    - pyramid-mailer==0.15.1
    - pysocks==1.7.1
    - python3-openid==3.2.0
    - pyyaml==5.3
    - rdflib==4.2.2
    - repoze-sendmail==4.4.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - runai==0.3.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - shapely==1.7.1
    - smplx==0.1.28
    - sqlalchemy==1.4.27
    - staintools==2.1.2
    - tabulate==0.8.6
    - termcolor==1.1.0
    - tifffile==2020.9.3
    - timm==0.4.9
    - torch==1.4.0
    - torchfile==0.1.0
    - torchvision==0.5.0
    - torchvision4ad==0.1.1
    - tqdm==4.43.0
    - transaction==3.0.1
    - translationstring==1.4
    - ttach==0.0.3
    - typeguard==2.9.1
    - typing-extensions==3.7.4.1
    - urllib3==1.25.8
    - velruse==1.1.1
    - venusian==3.0.0
    - vtk==8.1.2
    - webob==1.8.7
    - websocket-client==1.2.1
    - werkzeug==0.16.1
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - wtforms==3.0.0
    - wtforms-recaptcha==0.3.2
    - zope-deprecation==4.4.0
    - zope-interface==5.4.0
    - zope-sqlalchemy==1.6
